services:
  mysql:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
      target: dev
    ports:
      - '3306:3306'
    networks:
      - default
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/mysql/scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      # Check for the testing database to be ready, meaning the entrypoint script finished running
      test: mysql testing -uroot -proot --silent --execute "select 1;"
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: secret

  mongodb:
    build:
      context: ./docker/mongodb
      dockerfile: Dockerfile
      target: dev
    ports:
      - '27017:27017'
    networks:
      - default
    volumes:
      - mongodb-data:/data/db
      - ./docker/mongodb/scripts/init.js:/docker-entrypoint-initdb.d/init.js
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh admin -u root -p root --quiet
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: default

  monolith:
    build:
      context: ./monolith
      dockerfile: ./docker/app/Dockerfile
      target: dev
    ports:
      - '3000:3000'
    networks:
      - default
    volumes:
      - ./monolith/src:/app/src
      - ./monolith/config:/app/config
      - ./monolith/migrations/:/app/migrations
      - ./monolith/test:/app/test
      - ./monolith/.env:/app/.env
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # App settings
      HOST: 0.0.0.0
      PORT: 3000
      JWT_SECRET: secret
      # Database settings
      MYSQL_DATABASE_HOST: mysql
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE_USERNAME: app
      MYSQL_DATABASE_PASSWORD: secret
      MYSQL_DATABASE_TESTING_NAME: testing
      MYSQL_DATABASE_NAME: app
      MYSQL_DATABASE_LOGGING: true

  auth-fn:
    build:
      context: ./auth-fn
      dockerfile: ./docker/app/Dockerfile
      target: dev
    ports:
      - '8080:8080'
    networks:
      - default
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # App settings
      JWT_SECRET: secret
      # Database settings
      MYSQL_DATABASE_HOST: mysql
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE_USERNAME: app
      MYSQL_DATABASE_PASSWORD: secret
      MYSQL_DATABASE_NAME: app

  kitchen:
    build:
      context: ./kitchen
      dockerfile: ./docker/app/Dockerfile
      target: dev
    ports:
      - '3001:3000'
    networks:
      - default
    volumes:
      - ./kitchen/src:/app/src
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # App settings
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
      JWT_SECRET: secret
      # Database settings
      DATABASE_TYPE: mysql
      DATABASE_LOGGING: true
      DATABASE_SYNCHRONIZE: true
      MYSQL_DATABASE_HOST: mysql
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE_USERNAME: app
      MYSQL_DATABASE_PASSWORD: secret
      MYSQL_DATABASE_TESTING_NAME: testing
      MYSQL_DATABASE_NAME: kitchen

  order:
    build:
      context: ./order
      dockerfile: ./docker/app/Dockerfile
      target: dev
    ports:
      - '3002:3000'
    networks:
      - default
    volumes:
      - ./order/src:/app/src
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # App settings
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
      JWT_SECRET: secret
      PRODUCT_SERVICE_URL: http://kitchen:3000
      # Database settings
      DATABASE_TYPE: mysql
      DATABASE_LOGGING: true
      DATABASE_SYNCRONIZE: true
      MYSQL_DATABASE_HOST: mysql
      MYSQL_DATABASE_PORT: 3306
      MYSQL_DATABASE_USERNAME: app
      MYSQL_DATABASE_PASSWORD: secret
      MYSQL_DATABASE_TESTING_NAME: testing
      MYSQL_DATABASE_NAME: order

  payment:
    build:
      context: ./payment
      dockerfile: ./docker/app/Dockerfile
      target: dev
    ports:
      - '3003:3000'
    networks:
      - default
    volumes:
      - ./payment/src:/app/src
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      # App settings
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
      JWT_SECRET: secret
      ORDER_SERVICE_URL: http://order:3000
      # Database settings
      DATABASE_TYPE: mongodb
      DATABASE_LOGGING: true
      DATABASE_HOST: mongodb
      DATABASE_PORT: 27017
      DATABASE_USERNAME: payment
      DATABASE_PASSWORD: secret
      DATABASE_TESTING_NAME: testing
      DATABASE_NAME: payment

networks:
  default:
    driver: bridge

volumes:
  mysql-data:
  mongodb-data:
